---
kind: pipeline
type: docker
name: analysis

platform:
  arch: amd64
  os: linux
  
steps:
- name: linux cppcheck
  image: rikorose/gcc-cmake
  commands:
  - echo "static_check_number 1"
  depends_on: [ clone ]

- name: qnx cppcheck
  image: rikorose/gcc-cmake
  commands:
  - echo "static_check_number 2"
  depends_on: [ clone ]
  
- name: linux clang
  image: rikorose/gcc-cmake
  commands:
  - echo "static_check_number 3"
  depends_on: [ clone ]

- name: qnx clang 
  image: rikorose/gcc-cmake
  commands:
  - echo "static_check_number 4"
  depends_on: [ clone ]
  
---
kind: pipeline
type: docker
name: build

platform:
  arch: amd64
  os: linux
  
- name: linux debug
  image: rikorose/gcc-cmake
  commands:
  - echo "build job number 1"
  depends_on: [ clone ]

- name: qnx debug
  image: rikorose/gcc-cmake
  commands:
  - echo "build job number 2"
  depends_on: [ clone ]

depends_on:
- analysis
