---
kind: pipeline
type: docker
name: static check

platform:
  arch: amd64
  os: linux
  
steps:
- name: check: linux cppcheck
  image: rikorose/gcc-cmake
  commands:
  - echo "static_check_number 1"

- name: check: qnx cppcheck
  image: rikorose/gcc-cmake
  commands:
  - echo "static_check_number 2"
  
- name: check: linux clang
  image: rikorose/gcc-cmake
  commands:
  - echo "static_check_number 3"

- name: check: qnx clang 
  image: rikorose/gcc-cmake
  commands:
  - echo "static_check_number 4"
  
---
kind: pipeline
type: docker
name: build

platform:
  arch: amd64
  os: linux

steps:
- name: build_1
  image: rikorose/gcc-cmake
  commands:
  - echo "build job number 1"
  
- name: build_2
  image: rikorose/gcc-cmake
  commands:
  - echo "build job number 2" 
  
- name: build_3
  image: rikorose/gcc-cmake
  commands:
  - echo "build job number 3" 

- name: build_4
  image: rikorose/gcc-cmake
  commands:
  - echo "build job number 4" 

depends_on:
- static_check_1
- static_check_2
- static_check_3
- static_check_4
