---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux
  
steps:
- name: static check 1
  image: rikorose/gcc-cmake
  commands:
  - echo "static check #1"

- name: static check 2
  image: rikorose/gcc-cmake
  commands:
  - echo "static check #2"
  
- name: static check 3
  image: rikorose/gcc-cmake
  commands:
  - echo "static check #3"

- name: static check 4
  image: rikorose/gcc-cmake
  commands:
  - echo "static check #4"
  
- name: build 1 
  image: rikorose/gcc-cmake
  commands:
  - echo "build job #1"
  depends on:
  - static check 1
  - static check 2
  - static check 3
  - static check 4
  
- name: build 2
  image: rikorose/gcc-cmake
  commands:
  - echo "build job #2"
  depends on:
  - static check 1
  - static check 2
  - static check 3
  - static check 4  
  
- name: build 3
  image: rikorose/gcc-cmake
  commands:
  - echo "build job #3"
  depends on:
  - static check 1
  - static check 2
  - static check 3
  - static check 4
- name: build 4
  image: rikorose/gcc-cmake
  commands:
  - echo "build job #4"
  depends on:
  - static check 1
  - static check 2
  - static check 3
  - static check 4  
