---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux
  
steps:
- name: build
  image: conanio/gcc9
  commands:
  - whoami
  - pwd
  - ls -lath
  - ls -lath /
  - sudo mkdir build
  - cmake -GNinja -B build -S .
  - ./build/drone_ci
  
  when:
    event:
    - push
