---
kind: pipeline
type: docker
name: analysis

platform:
  arch: amd64
  os: linux
  
steps:
- name: linux cppcheck
  image: rikorose/gcc-cmake
  commands:
  - echo "static_check_number 1"

- name: qnx cppcheck
  image: rikorose/gcc-cmake
  commands:
  - echo "static_check_number 2"
  
- name: linux clang
  image: rikorose/gcc-cmake
  commands:
  - echo "static_check_number 3"

- name: qnx clang 
  image: rikorose/gcc-cmake
  commands:
  - echo "static_check_number 4"
  
---
kind: pipeline
type: docker
name: build

platform:
  arch: amd64
  os: linux

steps:
- name: linux release
  image: rikorose/gcc-cmake
  commands:
  - echo "build job number 1"
  when:
    event:
    - pull_request
  
- name: qnx release
  image: rikorose/gcc-cmake
  commands:
  - echo "build job number 2"
  when:
    event:
    - pull_request  
  
- name: linux debug
  image: rikorose/gcc-cmake
  commands:
  - echo "build job number 3"

- name: qnx debug
  image: rikorose/gcc-cmake
  commands:
  - echo "build job number 4"

depends_on:
- analysis
