---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux
  
steps:
- name: static_check_1
  image: rikorose/gcc-cmake
  commands:
  - echo "static_check_number 1"

- name: static_check_2
  image: rikorose/gcc-cmake
  commands:
  - echo "static_check_number 2"
  
- name: build_1
  image: rikorose/gcc-cmake
  commands:
  - echo "build job number 1"
  depends_on:
  - static_check_1
  - static_check_2
  
- name: build_2
  image: rikorose/gcc-cmake
  commands:
  - echo "build job number 2"
  depends_on:
  - static_check_1
  - static_check_2
