---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux
  
steps:
- name: build
  image: rikorose/gcc-cmake
  commands:
  - mkdir build
  - cmake -B build -S .
  - cd build && make -j4
  - ./drone_ci
  
  when:
    event:
    - push
