---
kind: pipeline
type: exec
name: linux-amd64

platform:
  arch: amd64
  os: linux
  
steps:
- name: build
  image: rikorose/gcc-cmake
  commands:
  - mkdir build && cd build
  - cmake -GNinja -B .. -S ../
  - ninja
  - ./drone_ci
  
  when:
    event:
    - push
